server:
  port: 8888

mybatis:
  mapper-locations: classpath:mapping/*.xml

spring:
  datasource:
    name: deal
    url: jdbc:mysql://127.0.0.1:3306/deal?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT
    username: root
    password: 123456
#   使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver

